### ISSUE TITLE
Add this template to Bevy Assets

### ISSUE THREAD

**Issue by benfrankel** [TheBevyFlock/bevy_quickstart#116]

**Comment by benfrankel** [comment]
Marking this as `blocked` because we'll want a screenshot, which should probably come after https://github.com/TheBevyFlock/bevy-template/issues/92.

**Comment by janhohenheim** [comment]
From Discord, this could be tge description:

> The template brought to you by the Bevy Jam Working Group.
> A great way to start working on a jam entry. Includes a basic project structure and automated deployments to itch.io

**Comment by janhohenheim** [comment]
I think I'll add a little video going from the application.

**Comment by janhohenheim** [comment]
Resolved by https://github.com/bevyengine/bevy-assets/pull/463
