### ISSUE TITLE
Automatically merge `main` into `cargo-generate` when a PR is merged

### ISSUE THREAD

**Issue by janhohenheim** [TheBevyFlock/bevy_quickstart#129]
Merge conflict could automatically open an issue.
If this is done via workflow, make sure it is excluded from `cargo-generate.toml` on the `cargo-generate` branch.
Assigning the local CI wizard ;p

**Comment by benfrankel** [comment]
Marking this as `wontfix` to wait until after Bevy Jam 5. We can do this manually for now.

**Comment by janhohenheim** [comment]
Assigning another notorious CI wizard. Feel free to ignore if you don't feel like it :)
