### ISSUE TITLE
Itch.io package names: Underscores converted to hyphens?

### ISSUE THREAD

**Issue by benfrankel** [TheBevyFlock/bevy_quickstart#157]
On itch.io:

![2024-07-17_1721254293_495x267](https://github.com/user-attachments/assets/ded0a914-6357-4fea-9db5-4509fc34eb84)

On GitHub release:

![2024-07-17_1721254574_300x185](https://github.com/user-attachments/assets/54c95fbf-35a9-41c2-bce4-f35c2afc96ad)

The downloaded filenames all match the filenames shown in the UI.

**Comment by benfrankel** [comment]
Needs investigation. May be only for `.zip` files, may be only on non-MacOS platforms, may be a known issue or intentional, etc.

**Comment by janhohenheim** [comment]
I tried googling but found nothing. I don't think there's much we can do here and it also doesn't seem a footgun to me, so I'll close this for now.
