### ISSUE TITLE
Improve user guidance on how to license Bevy logo

### ISSUE THREAD

**Issue by BD103** [TheBevyFlock/bevy_quickstart#172]
As far as I can tell, the Bevy logo does not have an explicit license. Please see https://github.com/bevyengine/bevy_github_ci_template/issues/45 for the reason it was removed from `bevy_ci_template`.

In this scenario, @cart will either have to sign-off that all people who use this template may use the logo in the splash screen, or it should unfortunately be removed.

**Comment by janhohenheim** [comment]
@alice-i-cecile I think we talked about its usage being fine for a splash screen as long as it's properly credited, but @BD103 is right, it's probably not CC0. Which license do we use?
