### ISSUE TITLE
`bevy/wayland` feature requires dependencies that may not be installed

### ISSUE THREAD

**Issue by benfrankel** [TheBevyFlock/bevy_quickstart#183]
This could be considered a documentation issue (docs should mention the required deps), or a bug (`bevy/wayland` should not be enabled for all builds).

Judging from https://github.com/bevyengine/bevy/pull/10792, it seems that always enabling `bevy/wayland` should be a reasonable choice / may become the upstream behavior, in which case this would be a documentation issue.

**Comment by janhohenheim** [comment]
Agreed on this being a documentation issue. Since this is the long-term default anyways, we should be prepared.

**Comment by janhohenheim** [comment]
Would it be enough to point to https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md ? It mentions the extra wayland deps.

**Comment by benfrankel** [comment]
Yeah that looks pretty good.

**Comment by digikata** [comment]
As an FYI, I'm on Linux PopOs 22.04 LTS and the template fails to find wayland-client (though it's installed).

I disabled the 'wayland' feature from the `bevy` dependency and the template built and ran fine.
