### ISSUE TITLE
`trunk build` fails without prior `cargo build` because of missing `target` dir

### ISSUE THREAD

**Issue by janhohenheim** [TheBevyFlock/bevy_quickstart#187]
Maybe we should go back to the default of using a `dist` dir in a known existing dir like `web` or just the crate root.

**Comment by benfrankel** [comment]
This should definitely be fixed upstream instead. How does `trunk build` not `mkdir -p` the `dist` dir? :confused:

**Comment by janhohenheim** [comment]
https://github.com/trunk-rs/trunk/issues/826

**Comment by janhohenheim** [comment]
Should work in the next trunk release :)
