### ISSUE TITLE
`design.md` links `bevy-design-patterns` as `bevy_best_practices` instead of `bevy-design-patterns`

### ISSUE THREAD

**Issue by TrialDragon** [TheBevyFlock/bevy_quickstart#189]
At [`design.md`](<https://github.com/TheBevyFlock/bevy_quickstart/blob/main/docs/design.md?plain=1#L35C5-L35C68>), `bevy-design-patterns` goes to `https://github.com/tbillington/bevy_best_practices` instead of the proper link of: `https://github.com/MiniaczQ/bevy-design-patterns` (I'm not entirely sure if this is the right link).

**Comment by janhohenheim** [comment]
@MiniaczQ would you prefer we remove it entirely? I have no problem linking to an outdated document, but it's yours, so your call :)

**Comment by MiniaczQ** [comment]
I'll try to get it updated with the few patterns that emerged and we can correct the link.
I'm fine with deleting it though, right now it serves no purpose
