### ISSUE TITLE
Write about what plugins even are

### ISSUE THREAD

**Issue by janhohenheim** [TheBevyFlock/bevy_quickstart#195]
Per @ChristopherBiscardi:
> for template feedback (or maybe not idk if it applies), I saw someone yesterday trying to order plugins to control when systems ran so that resources, etc were available when systems were running.
> Might be useful to have a brief piece of documentation introducing plugins?

I think that's a good idea for the design doc.

**Comment by benfrankel** [comment]
We assume the user knows how to use Bevy and has read the Quick Start guide, which includes a section on plugins: https://bevyengine.org/learn/quick-start/getting-started/plugins/. 

Explaining how plugins work is the responsibility of Bevy's documentation / guides, not this template. Explaining _how we're using_ plugins as a design pattern is fine.

**Comment by MiniaczQ** [comment]
Fully agreed with @benfrankel here, best I can suggest is stronger referrals of lower level learning resources

It's also a good idea to check if Bevy's Plugin documentation provides information about this

**Comment by janhohenheim** [comment]
Thought a bit more about this, and yeah, I think we are documenting all that we should already in this regard
