### ISSUE TITLE
`cargo generate` is not completing stuff in `index.html`

### ISSUE THREAD

**Issue by janhohenheim** [TheBevyFlock/bevy_quickstart#197]
This line stays unchanged post-generation:
```html
<title>{{project-name}}</title>
```

**Comment by Sapein** [comment]
It's probably from https://github.com/TheBevyFlock/bevy_quickstart/blob/394392d6dfaf25c72cf78cfc04194732ff3a0aa4/web/index.html#L28

Due to the `{` in there. So that should probably have a raw block around it.

**Comment by janhohenheim** [comment]
@Sapein good catch, that sounds like the culprit

**Comment by Sapein** [comment]
Yeah, I ran into this issue when setting up the Github Actions template stuff, which would cause `cargo generate` to just not error but not replace anything in a file if braces were/are present. 

I just never thought to double check the HTML stuff when I was doing that.

**Comment by benfrankel** [comment]
Hm, adding the `raw` block didn't seem to fix this: https://github.com/TheBevyFlock/bevy_quickstart/pull/227.

**Comment by benfrankel** [comment]
Resolved by https://github.com/TheBevyFlock/bevy_quickstart/pull/228.
