### ISSUE TITLE
Expand the workflows docs to mention the specific permissions needed

### ISSUE THREAD

**Issue by TrialDragon** [TheBevyFlock/bevy_quickstart#200]
> It would be nice to document which permission to add, and not to recommend adding a blanket write permission for everything. Anyone has any idea which permission exactly is missing in this particular case?

from djeedai on [Discord](https://discord.com/channels/691052431525675048/937158127491633152/1267169649896980521).

I figured it'd be a good thing to mention here for consideration.

**Comment by janhohenheim** [comment]
I think workflow files may be able to specify their permissions directly, in which case users do not need to tweak the settings at all. Not sure though.

**Comment by benfrankel** [comment]
Yeah I skimmed the documentation and it seems to suggest that. If true, that would be a UX improvement as well.

**Comment by janhohenheim** [comment]
Here's an example in the wild, courtesy of @bash: https://github.com/bash/bash.github.io/blob/main/.github/workflows/ci.yml#L43-L45
