### ISSUE TITLE
Workspace recommended extensions

### ISSUE THREAD

**Issue by wduminy** [TheBevyFlock/bevy_quickstart#201]
Would be nice to have the extensions mentioned in [tooling.md](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions) specified as [workspace recommended extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions).

**Comment by janhohenheim** [comment]
TIL about that feature, thanks!
