### ISSUE TITLE
Add VS Code snippets

### ISSUE THREAD

**Issue by benfrankel** [TheBevyFlock/bevy_quickstart#202]
For example, `component` can expand into:

```rust
#[derive(Component, Reflect)]
#[reflect(Component)]
struct _;
```

With cursor positioned on the `_`.

**Comment by janhohenheim** [comment]
Good idea. I'd personally add `Debug` and `reflect(Debug)` since you always want these in practice.

**Comment by benfrankel** [comment]
There are some existing Bevy code snippets in the VS Code Marketplace, but they're limited / archived on GitHub as far as I can tell.
