### ISSUE TITLE
Add `tiny_bail` to tooling recommendations

### ISSUE THREAD

**Issue by benfrankel** [TheBevyFlock/bevy_quickstart#204]
In my jam game, I used 4 macros: `r!`, `rq!`, `c!`, and `cq!`, read "return", "return quiet", "continue", and "continue quiet" respectively. Usage looks like this:

```rust
fn my_system(my_query: Query<&Foo, With<Bar>>) {
    let foo = r!(my_query.get_single());
    // ...
}
```

This will unwrap the `Option` if it's `Some`, or _log a warning_ (with a link to the exact line of code) and then return `default()` from the system if it's `None`. The macros all support an optional first argument with the value to return instead of `default()`, and can handle both `Option` and `Result` thanks to a trait that's impled for both of those types.

The quiet variants skip the warning, which is useful for cases that are "expected" to fail, like an observer that applies some optional effect if the entity it was triggered for contains a particular component.

Macros like this are definitely opinionated, but they help mitigate a pain point that every Bevy user experiences regarding error handling. I found them extremely convenient during the game jam.

**Comment by benfrankel** [comment]
Link to source: https://github.com/benfrankel/blobo_party/blob/main/src/util/macros.rs

**Comment by janhohenheim** [comment]
I personally love convenience macros like this, but I see that they add cognitive complexity and "strangeness" and are probably more opinionated than anything else in the template since they effectively change Bevy's syntax. 
Not saying "no", since I really really like these, but I'd like to hear an actual outsider's perspective first. Preferably, multiple people's opinions.

**Comment by benfrankel** [comment]
It seems that this belongs in a 3rd-party crate; and we can link to that crate in the tooling recommendations doc.

**Comment by benfrankel** [comment]
I released a crate for the macros: https://github.com/benfrankel/tiny_bail
