### ISSUE TITLE
Building binary out of a subfolder

### ISSUE THREAD

**Issue by cBournhonesque** [TheBevyFlock/bevy_quickstart#205]
My team's game https://github.com/cBournhonesque/jam5 started from the template, but i had a lot of CI issues because our binary is built in the `client` folder.
I made a couple of changes to the CI to account for that, but it took me a long time to figure them out

Maybe there could be an ENV in the release.yaml that specifies the folder containing the game

**Comment by benfrankel** [comment]
Agreed that we should be providing this functionality behind an `env` variable.

**Comment by benfrankel** [comment]
This is a duplicate of https://github.com/TheBevyFlock/bevy_quickstart/issues/194 actually.
