### ISSUE TITLE
Make the button audio slightly less abbrasive

### ISSUE THREAD

**Issue by janhohenheim** [TheBevyFlock/bevy_quickstart#208]
I noticed that a lot of the jam submissions kept the default button sounds which, over time, started to annoy me. Maybe we should switch to more "gentle" sounds and make them a bit more quiet?

**Comment by benfrankel** [comment]
There's something to be said about ugly UI / SFX in the template encouraging devs to replace them with their own. At the same time, I'm sure there are some users that just want to focus on building the "meat" of their game and would prefer a nicer default.

**Comment by janhohenheim** [comment]
If @Instelce if okay with it, maybe we could use the buttons from https://github.com/Instelce/postman-speed-race/. I quite like those :)
