### ISSUE TITLE
Investigate macOS crashes

### ISSUE THREAD

**Issue by janhohenheim** [TheBevyFlock/bevy_quickstart#209]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/0d7a53bd-535a-4a0b-a163-fa34dc12e6ac">

Note that the binary of `bevy_quickstart` itself does *not* crash.

**Comment by janhohenheim** [comment]
So far, these are affected:
- https://chrisbiscardi.itch.io/wash-cycle
- https://philiplinden.itch.io/bevy-jam-5

**Comment by janhohenheim** [comment]
@shanecelis is your code open sourced?

**Comment by shanecelis** [comment]
Yeah, MIT and Apache 2.0 unless otherwise noted.

**Comment by janhohenheim** [comment]
@shanecelis I'm asking because I couldn't find a link to it 😅

**Comment by janhohenheim** [comment]
Per @rparrett's [investigation](https://discord.com/channels/691052431525675048/1269334425494229012), this might be https://github.com/kaosat-dev/Blenvy/issues/214
