### ISSUE TITLE
Add `ui_debug_overlay` to `dev_tools.rs`, behind a toggle keybind

### ISSUE THREAD

**Issue by benfrankel** [TheBevyFlock/bevy_quickstart#211]
https://docs.rs/bevy/latest/bevy/dev_tools/ui_debug_overlay/index.html

**Comment by janhohenheim** [comment]
Great idea :D

**Comment by benfrankel** [comment]
There was some talk about putting the toggle in the settings menu for dev builds (after https://github.com/TheBevyFlock/bevy_quickstart/issues/213). That should be non-blocking however, since the button can be added with the settings PR, and the keybinding should probably remain afterwards as well.
