### ISSUE TITLE
Text on credits screen is awkwardly justified

### ISSUE THREAD

**Issue by rparrett** [TheBevyFlock/bevy_quickstart#220]
Text that flows onto multiple lines is left justified, but text that is one line only gets centered.

We should either add `with_text_justify(JustifyText::Center)` to the text, or remove `justify_content: JustifyContent::Center` from the label container.

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/dd8d4da1-3468-44e5-a8bf-d1729e42042a">

**Comment by benfrankel** [comment]
Alternatively, a grid layout could be nice (2 columns: right-aligned names, left-aligned descriptions).

**Comment by benfrankel** [comment]
This is resolved by https://github.com/TheBevyFlock/bevy_quickstart/pull/259. Better UI layouting will come in later PRs.
