### ISSUE TITLE
Add OnPress to button widget

### ISSUE THREAD

**Issue by Freyja-moth** [TheBevyFlock/bevy_quickstart#234]
Since each usage of the button widget has to add an on press afterwards it might be good to add an OnPress parameter to the method. 

This would also allow to take advantage of impl traits to reduce the footprint of spawning buttons if From<SystemId> is implemented for OnPress.

**Comment by janhohenheim** [comment]
Good idea! We can even make the param a `SystemId` directly, that way `OnPress` can be a hidden implementation detail :)

**Comment by benfrankel** [comment]
It can be a closure that gets registered internally as well.

**Comment by janhohenheim** [comment]
@benfrankel that's fancy 👀

**Comment by Freyja-moth** [comment]
@benfrankel just to check, are you talking about passing in a closure to the buttons method or am I thinking of something completely different?

**Comment by benfrankel** [comment]
Yeah, exactly that.
