### ISSUE TITLE
Potentential release workflow breakage due to CDN domain change

### ISSUE THREAD

**Issue by mnemotic** [TheBevyFlock/bevy_quickstart#255]
itch.io are migrating off `itch.ovh` CDN domain, to `itch.zone`. They are recommending to use the new domain for downloading `butler`, see https://github.com/itchio/butler/issues/257#issuecomment-1832707482. It's unclear how long `itch.ovh` will remain available.

"Install butler" step in `release.yaml` workflow file should be updated to use `itch.zone` domain in order to avoid future breakage.

I can open a PR if there are no objections.

**Comment by benfrankel** [comment]
A PR would be appreciated, thanks for catching this before it became a problem :)

**Comment by janhohenheim** [comment]
Thanks for the heads-up, appreciate it :)

**Comment by mnemotic** [comment]
You're welcome. 😄
