### ISSUE TITLE
Authentication needed for https://github.com/TheBevyFlock/bevy-quickstart.git

### ISSUE THREAD

**Issue by imding** [TheBevyFlock/bevy_quickstart#299]
I get this when I run `cargo generate TheBevyFlock/bevy-quickstart --branch cargo-generate` as suggested in the README.md and my Github credentials doesn't work for this.

```
Authentication needed for https://github.com/TheBevyFlock/bevy-quickstart.git
```

**Comment by kristoferssolo** [comment]
The command is `cargo generate TheBevyFlock/bevy_quickstart --branch cargo-generate`. There should be an underscore (`_`) not minus (`-`).

**Comment by benfrankel** [comment]
Nice catch. That's an unhelpful error message on `cargo-generate`'s end... maybe an issue can be opened there.

**Comment by janhohenheim** [comment]
At least this won't be a problem with `bevy new 2d`

**Comment by benfrankel** [comment]
Opened issue on `cargo-generate`: https://github.com/cargo-generate/cargo-generate/issues/1278
