### ISSUE TITLE
Replace `{{project-name}}` with `{{crate_name}}` in audio.rs

### ISSUE THREAD

**Issue by kristoferssolo** [TheBevyFlock/bevy_quickstart#306]
In `cargo-generate` branch, in the `src/audio.rs` file, there are code examples in the documentation for the Music and SoundEffect components that use incorrect placeholders. The current placeholders `{{project-name}}` should be replaced with `{{crate_name}}`.

**Comment by benfrankel** [comment]
Ah, true. We don't want hyphens there. Thanks :)

**Comment by benfrankel** [comment]
Fixed with https://github.com/TheBevyFlock/bevy_quickstart/commit/33c9cc6f68afdd50948b19169b1a340ed84d6ec5.
